### ISSUE TITLE
无法同时设置 loading 和 disabled

### ISSUE THREAD

**Issue by shurong-wang** [react-native-component/react-native-smart-button#1]
在提交表单中时，想显示“按钮置灰 + 显示 loading”。实际效果没有 loading。只有在不设置 disabled 时才能显示 loading。

**Comment by cyqresig** [comment]
您好，按钮在loading状态时，与在disabled状态时一样touch事件将不会生效。loading状态和disabled状态是没有关联的二个状态，并不能同时存在

**Comment by shurong-wang** [comment]
好的，我理解了，非常感谢。您的 react-native-smart-* 系列项目都非常实用，后面会继续关注~
